/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as ReduxRouteImport } from './routes/redux'
import { Route as NanostoresRouteImport } from './routes/nanostores'
import { Route as JotaiRouteImport } from './routes/jotai'
import { Route as IndexRouteImport } from './routes/index'

const rootRouteImport = createRootRoute()

const ReduxRoute = ReduxRouteImport.update({
  id: '/redux',
  path: '/redux',
  getParentRoute: () => rootRouteImport,
} as any)
const NanostoresRoute = NanostoresRouteImport.update({
  id: '/nanostores',
  path: '/nanostores',
  getParentRoute: () => rootRouteImport,
} as any)
const JotaiRoute = JotaiRouteImport.update({
  id: '/jotai',
  path: '/jotai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jotai': typeof JotaiRoute
  '/nanostores': typeof NanostoresRoute
  '/redux': typeof ReduxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jotai': typeof JotaiRoute
  '/nanostores': typeof NanostoresRoute
  '/redux': typeof ReduxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jotai': typeof JotaiRoute
  '/nanostores': typeof NanostoresRoute
  '/redux': typeof ReduxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jotai' | '/nanostores' | '/redux'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jotai' | '/nanostores' | '/redux'
  id: '__root__' | '/' | '/jotai' | '/nanostores' | '/redux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JotaiRoute: typeof JotaiRoute
  NanostoresRoute: typeof NanostoresRoute
  ReduxRoute: typeof ReduxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redux': {
      id: '/redux'
      path: '/redux'
      fullPath: '/redux'
      preLoaderRoute: typeof ReduxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nanostores': {
      id: '/nanostores'
      path: '/nanostores'
      fullPath: '/nanostores'
      preLoaderRoute: typeof NanostoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jotai': {
      id: '/jotai'
      path: '/jotai'
      fullPath: '/jotai'
      preLoaderRoute: typeof JotaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JotaiRoute: JotaiRoute,
  NanostoresRoute: NanostoresRoute,
  ReduxRoute: ReduxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
